---
- hosts: dev-a
  remote_user: root
  become: yes
  vars_files:
    - secret.yml
  vars:
    - destdir: /app/example

  tasks:
  - name: update apt and upgrade all packages
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: clone a repo github
    git:
      repo: https://{{gittoken}}@github.com/example.git
      dest: "{{destdir}}"
      clone: yes
      update: yes
  
  - name: pull a repo github
    git:
      repo: (url)
      dest: "{{destdir}}"
      clone: no
      update: yes

      