---
- hosts: dev-a
  remote_user: root
  become: yes

 

  tasks:
  - name: update apt and upgrade all packages
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: clone a github repository
    git:
      repo: https://{{gittoken}}@github.com/example.git
      dest: "{{destdir}}"
      clone: yes
      update: yes
  
  - name: pull a github repository
    git:
      repo: (url)
      dest: "{{destdir}}"
      clone: no
      update: yes
      version: master

      
